version: "3.9"

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    networks:
      - test-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  test-runner:
    build: .
    depends_on:
      - postgres-db
    container_name: test-runner
    networks:
      - test-network
    volumes:
      - .:/app

networks:
  test-network:

volumes:
  postgres-data:
