name: Python Tests

# Запуск workflow при пуші або PR у гілку homework31
on:
  push:
    branches:
      - homework31
  pull_request:
    branches:
      - homework31

jobs:
  test:
    runs-on: ubuntu-latest  # Використовуємо Ubuntu runner

    steps:
    # 1. Клонування репозиторію
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Встановлення Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # 3. Встановлення залежностей з requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Запуск тестів і збір Allure результатів
    # Тести запускаються тільки з кореня репозиторію (де лежить test_dummy.py)
    - name: Run tests
      run: |
        pytest . --alluredir=allure-results

    # 5. Встановлення Node.js (потрібно для Allure CLI)
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    # 6. Встановлення Allure CLI через NPM
    - name: Install Allure CLI
      run: |
        npm install -g allure-commandline --save-dev

    # 7. Генерація HTML-звіту Allure
    - name: Generate Allure Report
      run: |
        allure generate allure-results -o allure-report --clean

    # 8. Завантаження HTML-звіту як артефакт
    - name: Upload Allure HTML report
      uses: actions/upload-artifact@v4
      with:
        name: allure-html-report
        path: allure-report/
