name: Python Tests

on:
  push:
    branches:
      - homework31
  pull_request:
    branches:
      - homework31

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Клонування репозиторію
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Встановлення Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # 3. Встановлення залежностей
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install allure-pytest

    # 4. Запуск тестів з генерацією Allure результатів
    - name: Run tests
      run: |
        pytest --alluredir=allure-results

    # 5. Публікація Allure результатів як артефакт
    - name: Upload Allure results
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: allure-results/
